CREATE TABLE [dbo].[MASTER_ITEM_DOCUMENT_HISTORY](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ITEM_DOCUMENT_ID] [int] NOT NULL,
	[ITEM_CODE] [nvarchar](14) NOT NULL,
	[remarks] [nvarchar](500) NULL,
	[ACTION] [nvarchar](40) NOT NULL,
	[FILE] [nvarchar](250) NULL,
	[PATHS] [nvarchar](500) NULL,
	[CRE_BY] [nvarchar](15) NULL,
	[CRE_DATE] [datetime] NULL,
	[CRE_IP_ADDRESS] [nvarchar](15) NULL,
	[MOD_BY] [nvarchar](15) NULL,
	[MOD_DATE] [datetime] NULL,
	[MOD_IP_ADDRESS] [nvarchar](15) NULL,
 CONSTRAINT [PK_MASTER_ITEM_DOCUMENT_HISTORY] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO