CREATE TABLE [dbo].[TERM_OF_PAYMENT_DETAIL](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PO_CODE] [nvarchar](50) NULL,
	[TRX_CODE] [nvarchar](50) NULL,
	[ITEM_CODE] [nvarchar](50) NULL,
	[UNIT_PRICE_TRM] [decimal](18, 2) NULL,
	[ORDER_QTY] [decimal](18, 2) NULL,
	[PPN_TRM] [decimal](18, 2) NULL,
	[PPH_TRM] [decimal](18, 2) NOT NULL,
	[DISCOUNT_TERM] [decimal](18, 2) NULL,
	[FEE_TERM] [decimal](18, 2) NULL,
	[ADDITIONAL_TERM] [decimal](18, 2) NULL,
	[TOTAL_PO_AMOUNT] [decimal](18, 2) NULL,
	[TOTAL_AMOUNT_TERMIN] [decimal](18, 2) NULL,
	[OUTSTANDING_PO_AMOUNT] [decimal](18, 2) NULL,
	[CRE_DATE] [datetime] NOT NULL,
	[CRE_BY] [nvarchar](15) NOT NULL,
	[CRE_IP_ADDRESS] [nvarchar](15) NOT NULL,
	[MOD_DATE] [datetime] NOT NULL,
	[MOD_BY] [nvarchar](15) NOT NULL,
	[MOD_IP_ADDRESS] [nvarchar](15) NOT NULL,
 CONSTRAINT [PK_TERM_OF_PAYMENT_DETAIL] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


