CREATE TABLE [dbo].[FA_GROUPING_ASSET_DETAIL](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FA_GA_CODE] [nvarchar](20) NOT NULL,
	[FA_ASSET_ID] [int] NULL,
	[CODE_ASSET] [nvarchar](18) NULL,
	[NAME_ASSET] [nvarchar](60) NOT NULL,
	[BARCODE] [nvarchar](20) NOT NULL,
	[DESCRIPTION] [nvarchar](200) NULL,
	[IS_PARENT] [bit] NOT NULL,
	[IS_ACTIVE] [bit] NOT NULL,
	[CRE_DATE] [datetime] NOT NULL,
	[CRE_BY] [nvarchar](15) NOT NULL,
	[CRE_IP_ADDRESS] [nvarchar](15) NOT NULL,
	[MOD_DATE] [datetime] NOT NULL,
	[MOD_BY] [nvarchar](15) NOT NULL,
	[MOD_IP_ADDRESS] [nvarchar](15) NOT NULL,
 CONSTRAINT [PK_FA_GROUPING_ASSET_DETAIL] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[FA_GROUPING_ASSET_DETAIL] ADD  CONSTRAINT [DF_FA_GROUPING_ASSET_DETAIL_IS_PARENT]  DEFAULT ((0)) FOR [IS_PARENT]
GO

ALTER TABLE [dbo].[FA_GROUPING_ASSET_DETAIL] ADD  CONSTRAINT [DF_FA_GROUPING_ASSET_DETAIL_IS_ACTIVE]  DEFAULT ((1)) FOR [IS_ACTIVE]
GO


