IF NOT EXISTS (
    SELECT 1 
    FROM dbo.MASTER_LOOKUP_COLUMN 
    WHERE LOOKUP_CODE = 'FGAMV' AND FIELD_NAME = 'FA_GROUP_ASSET_CODE'
)
BEGIN
    INSERT INTO dbo.MASTER_LOOKUP_COLUMN
    (
        LOOKUP_CODE, ORDER_NO, FIELD_NAME, HEADER_NAME, WIDTH_PCT, 
        ALIGNMENT, [FORMAT], IS_VISIBLE, IS_DATAKEY, 
        CRE_DATE, CRE_BY, CRE_IP_ADDRESS, MOD_DATE, MOD_BY, MOD_IP_ADDRESS
    )
    VALUES
    (
        'FGAMV', 0, 'FA_GROUP_ASSET_CODE', 'Asset Group Code', 40, 
        'Left', '', '1', '1', 
        GETDATE(), '1000000001', '127.0.0.1', GETDATE(), '1000000001', '127.0.0.1'
    );
    PRINT 'Kolom FA_GROUP_ASSET_CODE berhasil ditambahkan.';
END
ELSE
BEGIN
    PRINT 'Kolom FA_GROUP_ASSET_CODE sudah ada di database.';
END;

IF NOT EXISTS (
    SELECT 1 
    FROM dbo.MASTER_LOOKUP_COLUMN 
    WHERE LOOKUP_CODE = 'FGAMV' AND FIELD_NAME = 'FA_GROUP_ASSET_NAME'
)
BEGIN
    INSERT INTO dbo.MASTER_LOOKUP_COLUMN
    (
        LOOKUP_CODE, ORDER_NO, FIELD_NAME, HEADER_NAME, WIDTH_PCT, 
        ALIGNMENT, [FORMAT], IS_VISIBLE, IS_DATAKEY, 
        CRE_DATE, CRE_BY, CRE_IP_ADDRESS, MOD_DATE, MOD_BY, MOD_IP_ADDRESS
    )
    VALUES
    (
        'FGAMV', 1, 'FA_GROUP_ASSET_NAME', 'Asset Group Name', 60, 
        'Left', '', '1', '1', 
        GETDATE(), '1000000001', '127.0.0.1', GETDATE(), '1000000001', '127.0.0.1'
    );
    PRINT 'Kolom FA_GROUP_ASSET_NAME berhasil ditambahkan.';
END
ELSE
BEGIN
    PRINT 'Kolom FA_GROUP_ASSET_NAME sudah ada di database.';
END;