CREATE TABLE [dbo].[FA_GROUPING_ASSET](
	[FA_GROUP_ASSET_CODE] [nvarchar](10) NOT NULL,
	[FA_GROUP_ASSET_NAME] [nvarchar](100) NOT NULL,
	[REMARKS] [nvarchar](100) NULL,
	[BRANCH_CODE] [nvarchar](10) NULL,
	[FA_LOCATION] [nvarchar](10) NULL,
	[IS_ACTIVE] [bit] NOT NULL,
	[CRE_DATE] [datetime] NOT NULL,
	[CRE_BY] [nvarchar](15) NOT NULL,
	[CRE_IP_ADDRESS] [nvarchar](15) NOT NULL,
	[MOD_DATE] [datetime] NOT NULL,
	[MOD_BY] [nvarchar](15) NOT NULL,
	[MOD_IP_ADDRESS] [nvarchar](15) NOT NULL,
	[GROUP_ASSET_SEQUENCE] [nvarchar](4) NOT NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[FA_GROUPING_ASSET] ADD  CONSTRAINT [DF_FA_GROUPING_ASSET_IS_ACTIVE]  DEFAULT ((1)) FOR [IS_ACTIVE]
GO

