CREATE TABLE [dbo].[FA_GROUPING_ASSET_HISTORY](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FA_GA_DETAIL_ID] [int] NOT NULL,
	[BARCODE] [nvarchar](20) NOT NULL,
	[ACTION] [nvarchar](20) NOT NULL,
	[MOVE_TO] [nvarchar](200) NULL,
	[DOC_REFF_NO] [NVARCHAR](200) NULL,
	[CRE_DATE] [datetime] NOT NULL,
	[CRE_BY] [nvarchar](15) NOT NULL,
	[CRE_IP_ADDRESS] [nvarchar](15) NOT NULL,
	[MOD_DATE] [datetime] NOT NULL,
	[MOD_BY] [nvarchar](15) NOT NULL,
	[MOD_IP_ADDRESS] [nvarchar](15) NOT NULL,
 CONSTRAINT [PK_FA_GROUPING_ASSET_HISTORY] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]
GO


