IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_FA_GROUPING_ASSET_CODE_ACTIVE'
      AND object_id = OBJECT_ID('dbo.FA_GROUPING_ASSET')
)
BEGIN
    CREATE NONCLUSTERED INDEX IX_FA_GROUPING_ASSET_CODE_ACTIVE
    ON dbo.FA_GROUPING_ASSET (FA_GROUP_ASSET_CODE, IS_ACTIVE)
    INCLUDE (FA_GROUP_ASSET_NAME, BRANCH_CODE, FA_LOCATION, MOD_DATE);
END
GO

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_FA_GROUPING_ASSET_BRANCH_LOCATION_ACTIVE'
      AND object_id = OBJECT_ID('dbo.FA_GROUPING_ASSET')
)
BEGIN
    CREATE NONCLUSTERED INDEX IX_FA_GROUPING_ASSET_BRANCH_LOCATION_ACTIVE
    ON dbo.FA_GROUPING_ASSET (BRANCH_CODE, FA_LOCATION, IS_ACTIVE, MOD_DATE)
    INCLUDE (FA_GROUP_ASSET_CODE, FA_GROUP_ASSET_NAME);
END
GO

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_FA_GROUPING_ASSET_detail_BARCODE_ACTIVE'
      AND object_id = OBJECT_ID('dbo.FA_GROUPING_ASSET_DETAIL')
)
BEGIN
    CREATE NONCLUSTERED INDEX IX_FA_GROUPING_ASSET_detail_BARCODE_ACTIVE
    ON dbo.FA_GROUPING_ASSET_DETAIL (FA_GA_CODE, IS_PARENT, BARCODE, IS_ACTIVE);
END
GO

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_FA_GROUPING_ASSET_DETAIL_BARCODE_ACTIVE'
      AND object_id = OBJECT_ID('dbo.FA_GROUPING_ASSET_DETAIL')
)
BEGIN
    CREATE NONCLUSTERED INDEX IX_FA_GROUPING_ASSET_DETAIL_BARCODE_ACTIVE
    ON dbo.FA_GROUPING_ASSET_DETAIL (BARCODE, IS_ACTIVE, FA_GA_CODE)
    INCLUDE (ID, FA_ASSET_ID, IS_PARENT, CODE_ASSET, NAME_ASSET);
END
GO

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_FA_GROUPING_ASSET_DETAIL_GA_ACTIVE_ASSET'
      AND object_id = OBJECT_ID('dbo.FA_GROUPING_ASSET_DETAIL')
)
BEGIN
    CREATE NONCLUSTERED INDEX IX_FA_GROUPING_ASSET_DETAIL_GA_ACTIVE_ASSET
    ON dbo.FA_GROUPING_ASSET_DETAIL (FA_GA_CODE, IS_ACTIVE, FA_ASSET_ID, IS_PARENT)
    INCLUDE (ID, BARCODE);
END
GO

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_FA_GROUPING_ASSET_HISTORY_DETAIL_BARCODE_DATE'
      AND object_id = OBJECT_ID('dbo.FA_GROUPING_ASSET_HISTORY')
)
BEGIN
    CREATE NONCLUSTERED INDEX IX_FA_GROUPING_ASSET_HISTORY_DETAIL_BARCODE_DATE
    ON dbo.FA_GROUPING_ASSET_HISTORY (FA_GA_DETAIL_ID, BARCODE, MOD_DATE)
    INCLUDE (ACTION, MOVE_TO, DOC_REFF_NO, CRE_DATE, MOD_BY);
END
GO

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_FA_SALE_DETAIL_CODE_BARCODE'
      AND object_id = OBJECT_ID('dbo.FA_SALE_DETAIL')
)
BEGIN
    CREATE NONCLUSTERED INDEX IX_FA_SALE_DETAIL_CODE_BARCODE
    ON dbo.FA_SALE_DETAIL (FA_SALE_CODE, BARCODE)
    INCLUDE (ID, FA_ASSET_ID, CODE_ASSET, NAME_ASSET, SALE_VALUE);
END
GO

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_FA_DISPOSAL_DETAIL_CODE_BARCODE'
      AND object_id = OBJECT_ID('dbo.FA_DISPOSAL_DETAIL')
)
BEGIN
    CREATE NONCLUSTERED INDEX IX_FA_DISPOSAL_DETAIL_CODE_BARCODE
    ON dbo.FA_DISPOSAL_DETAIL (FA_DISPOSAL_CODE, BARCODE)
    INCLUDE (ID, FA_ASSET_ID, CODE_ASSET, NAME_ASSET);
END
GO

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_FA_REQUEST_MUTATION_DETAIL_IR_ITEM'
      AND object_id = OBJECT_ID('dbo.FA_REQUEST_MUTATION_DETAIL')
)
BEGIN
    CREATE NONCLUSTERED INDEX IX_FA_REQUEST_MUTATION_DETAIL_IR_ITEM
    ON dbo.FA_REQUEST_MUTATION_DETAIL (IR_CODE, ITEM_CODE)
    INCLUDE (ID, STATUS_RECEIVED);
END
GO

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_FA_ASSET_BARCODE_STATUS_LOCATION'
      AND object_id = OBJECT_ID('dbo.FA_ASSET')
)
BEGIN
    CREATE NONCLUSTERED INDEX IX_FA_ASSET_BARCODE_STATUS_LOCATION
    ON dbo.FA_ASSET (BARCODE, TRANS_FLAG_CODE, CURRENT_BRANCH, BRANCH_CODE)
    INCLUDE (ID, AST_CODE, AST_NAME, CAT_CODE, ORIG_PRICE, NET_BOOK_VALUE);
END
GO

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_INVENTORY_BARCODE_STATUS_RENT_LOOKUP'
      AND object_id = OBJECT_ID('dbo.INVENTORY_BARCODE')
)
BEGIN
    CREATE NONCLUSTERED INDEX IX_INVENTORY_BARCODE_STATUS_RENT_LOOKUP
    ON dbo.INVENTORY_BARCODE (BARCODE_STATUS, BARCODE, ITEM_CODE)
    INCLUDE (BRANCH_CODE, LOCATION_CODE);
END
GO
